# Generated by Django 4.2.2 on 2023-06-11 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pereval.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, max_length=32, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, max_length=32, null=True, verbose_name='Долгота')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('', 'Не задано'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3b*', '3Б*')], default='', max_length=5, verbose_name='Зима')),
                ('summer', models.CharField(choices=[('', 'Не задано'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3b*', '3Б*')], default='', max_length=5, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('', 'Не задано'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3b*', '3Б*')], default='', max_length=5, verbose_name='Осень')),
                ('spring', models.CharField(choices=[('', 'Не задано'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3b*', '3Б*')], default='', max_length=5, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('fam', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('otc', models.CharField(blank=True, max_length=64, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('beauty_title', models.CharField(default='пер.', max_length=255, verbose_name='Префикс')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другое название')),
                ('connect', models.TextField(blank=True, null=True, verbose_name='Что соединяет')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending ', 'Модерируется'), ('accepted', 'Принят'), ('rejected', 'Не принят')], default='new', max_length=8, verbose_name='Статус')),
                ('coords', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='pereval.user')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data', models.ImageField(blank=True, null=True, upload_to=pereval.models.get_image_path, verbose_name='Изображение')),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.passage')),
            ],
        ),
    ]
